name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"     # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Ensure there is always a change
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt

      - name: Commit and push snake.svg
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake.svg animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify commit
        run: |
          git log -1 --pretty=format:'%s'
